version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: tezgah
    volumes:
      - ./mysql-data:/var/lib/mysql